version: '3'
services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: ts-node-docker
    ports:
      - 3000:3000
    command: npm run dev